name: Scheduled Run

on:
  workflow_dispatch:
  # Событие, которое запускает Пайплайн
  schedule:
    - cron: 30 15 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Забираем код из удаленного репозитория  
      - uses: actions/checkout@v4

      # Установка Node.js для работы с npm (чтобы потом установить Newman)
      - name: Use Node.js
        uses: actions/setup-node@v4

      # Установка Newman и html reporter
      - name: Install Newman 
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
     
      # Запуск Postman коллекции в Newman 
      - name: Run Postman collection 
        run: 'newman run Andrey_Trello.postman_collection.json -e TRELLO_Andrey.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export trello_report.html'

        # Убедится, что отчет создан 
      - name: Chech Files
        run: 'ls' 
        
        #Прикрепление отчета к тестовому прогону 
      - name: Upload Artifact1
        uses: actions/upload-artifact@v4 
        with:
            name: Reports
            path: "*html"
            
        #Отправка отчета на почтовый адрес
      - name: Send a report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: ${{secrets.MAIL_USERNAME}} 
            password: ${{secrets.MAIL_PASSWORD}}
            to: rudakovandrey909@gmail.com
            subject: Test report
            from: GitHub Actions <actions@example.com>
            attachments: trello_report.html


   
         
