name: Scheduled Run

on:
  workflow_dispatch:
  # Событие, которое запускает Пайплайн
  schedule:
    - cron: 30 15 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Забираем код из удаленного репозитория  
      - uses: actions/checkout@v4

      # Установка Node.js для работы с npm (чтобы потом установить Newman)
      - name: Use Node.js
        uses: actions/setup-node@v4

      # Установка Newman и html reporter
      - name: Install Newman 
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
     
      # Запуск Postman коллекции в Newman 
      - name: Run Postman collection 
        run: 'newman run Andrey_Trello.postman_collection.json -e TRELLO_Andrey.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export trello_report.html'

      # Просмотр отчета в папке 
       - name: Мiewing the contents of a folder
        run: |
          ls /Trello_API_testing/edit/master/.github/workflows/Scheduled_run.yml
        
         
